services:
  mongo:
    image: mongo:7.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_APP_USER: ${MONGO_APP_USER}
      MONGO_APP_PASSWORD: ${MONGO_APP_PASSWORD}
      MONGO_READ_USER: ${MONGO_READ_USER}
      MONGO_READ_PASSWORD: ${MONGO_READ_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [
          "CMD", "mongosh", "--quiet",
          "mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@localhost:27017/admin",
          "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      timeout: 3s
      retries: 30

  migrate:
    build: .
    container_name: mongo_migration
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      MONGO_URI: mongodb://${MONGO_APP_USER}:${MONGO_APP_PASSWORD}@mongo:27017/${MONGO_DB}?authSource=${MONGO_DB}
      MONGO_DB: ${MONGO_DB}
      MONGO_COLLECTION: admissions
    volumes:
      - csv_data:/app/data:ro
    command: ["python", "migrate_csv_to_mongodb.py", "--csv", "/app/data/healthcare_dataset.csv", "--batch-size", "5000"]

volumes:
  mongo_data:
  csv_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data